apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-production
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: mnaiem262/calculator:latest
        ports:
        - containerPort: 5000
