apiVersion: v1
kind: Service
metadata:
  name: calculator-production
  namespace: production
spec:
  type: NodePort
  selector:
    app: calculator
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31586
