apiVersion: v1
kind: Service
metadata:
  name: calculator-staging
  namespace: staging
spec:
  type: NodePort
  selector:
    app: calculator
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31585
