name: CI/CD to Minikube

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  build-deploy:
    runs-on: self-hosted  # your local runner with Docker + kubectl + Minikube
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set Docker credentials as env vars
      run: |
        echo "DOCKER_USER=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
        echo "DOCKER_PASS=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

    - name: Set Image Tag
      id: tag
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          TAG=${{ github.event.inputs.environment }}
        else
          TAG="staging"
        fi
        echo "IMAGE_TAG=$DOCKER_USER/calculator:$TAG" >> $GITHUB_ENV
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -t $IMAGE_TAG .

    - name: Push Docker image
      run: docker push $IMAGE_TAG

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -n $TAG -f k8s/deployment-$TAG.yaml
        kubectl apply -n $TAG -f k8s/service-$TAG.yaml

    - name: Show service URL
      run: minikube service calculator-$TAG -n $TAG --url
